### ISSUE TITLE
Documentation and installing

### ISSUE THREAD

**Issue by quackduck** [KhushrajRathod/repl.deploy#1]
I have some suggestions/questions:
1. Explain what `run="./repl.deploy --standalone node index.js"` does exactly
2. Explain what the `/refresh` ending means.
3. Does it need to be downloaded every time? Can I just download it once? Do I have to use this link which is not a https://github.com link: https://repl-deploy.vercel.app/? (people might ask this for security reasons)

**Comment by khrj** [comment]
This isn't completely done yet, so I'll add docs for your mentioned points soon 🙌 

(just listing stuff here, I'll add this to the docs)

>  Explain what `run="./repl.deploy --standalone node index.js"` does exactly

Makes the repl.it `Run` button run the daemon instead of the command directly, which then executes/re-executes on git push

>  Explain what the `/refresh` ending means.

That's just a random endpoint which I chose for this ¯\\\_(ツ)\_/¯ 

> Does it need to be downloaded every time? Can I just download it once?

Just needs to be downloaded once.

> Do I have to use this link which is not a https://github.com link: https://repl-deploy.vercel.app/? (people might ask this for security reasons)

You don't have to, but it saves you the time of going to releases and manually finding the link to the assets, since github provides no way to link to a particular asset in the latest release automatically

**Comment by khrj** [comment]
https://github.com/KhushrajRathod/repl.deploy/commit/1d192ed9892f0a4d06ff36c6330c50f6d6c605ce

**Comment by quackduck** [comment]
Okay wait in the docs you say it needs to be downloaded for each repl. Why is that? Why can't I download once and just copy the download to each repl?

**Comment by khrj** [comment]
> Why can't I download once and just copy the download to each repl?

Because like... you can't copy files across repls?

**Comment by quackduck** [comment]
Oh yeah LOL

**Comment by quackduck** [comment]
If I understand correctly, running `./repl.deploy --standalone node index.js` will first sync GitHub and Repl and then run `node index.js`

**Comment by khrj** [comment]
No, it won't sync with GitHub immediately, that happens when you commit -- I don't want people to lose any changes before they've set up git properly

**Comment by quackduck** [comment]
You should probably say that the `node index.js` part can be changed by the user (for different languages). Some repls may even have multiline run configs so you should probably have a command that only syncs and does not run anaything. Then you can tell the user to just add `./repl.deploy` before the rest of their config.

**Comment by khrj** [comment]
> You should probably say that the node index.js part can be changed by the user (for different languages). 

It says exactly that? (+it says that `node index.js` is an example)

![Screenshot 2021-03-16 at 10 25 18 AM](https://user-images.githubusercontent.com/44947946/111257969-15677f80-8642-11eb-8ec4-e0784a5af5df.png)

> Some repls may even have multiline run configs so you should probably have a command that only syncs and does not run anaything

That wouldn't work, the user would have to manually start the repl which defeats the purpose.

**Comment by quackduck** [comment]
> That wouldn't work, the user would have to manually start the repl which defeats the purpose.

I said this: "Then you can tell the user to just add ./repl.deploy before the rest of their config."

> It says exactly that? (+it says that node index.js is an example)

I'm extremely stupid, I missed that lol

**Comment by quackduck** [comment]
Instead of your command running the run command, it would be better design to have the user make it a multi-command run command: `run="repl.deploy; <user's command>"`

**Comment by khrj** [comment]
> Instead of your command running the run command, it would be better design to have the user make it a multi-command run command: run="repl.deploy; <user's command>"

Yeah but how is `repl.deploy` supposed to know what the user's command is then? To restart it when updating from git?

**Comment by quackduck** [comment]
Nah, repl itself will run the user's command.

**Comment by khrj** [comment]
Yes but how do I get repl.it to do that??

**Comment by khrj** [comment]
Whoops, didn't mean to reopen

**Comment by quackduck** [comment]
Replit just runs whatever you put in `run=""`, so all you do is tell the user to put in something like `run="repl.deploy; go run main.go"` and then Replit will first run `repl.deploy` and then `go run main.go`!

**Comment by khrj** [comment]
> Replit just runs whatever you put in run="", so all you do is tell the user to put in something like run="repl.deploy; go run main.go" and then Replit will first run repl.deploy and then go run main.go!

That's incorrect -- Replit runs whatever is there in the `run=""` _when the user clicks the `Run` button_. The whole point is to not get the user to go to repl.it and deploy from GitHub directly.

**Comment by quackduck** [comment]
> when the user clicks the Run button

Yeah so how does setting `run="./repl.deploy --standalone node index.js"` make a difference? It will also run when the user clicks run.

So the point of this thing is to be able to use GitHub, but also to deploy it on Replit's servers.

**Comment by khrj** [comment]
> So the point of this thing is to be able to use GitHub, but also to deploy it on Replit's servers.

Precisely. Replit here isn't to host code, but to deploy it.

**Comment by quackduck** [comment]
What about:
> Yeah so how does setting run="./repl.deploy --standalone node index.js" make a difference? It will also run when the user clicks run.

**Comment by khrj** [comment]
Yes, but that'll run forever, so the user only needs to run it _once_ (While setting up `repl.deploy`). When you have it the other way, the user needs to run it every time they push code.

**Comment by quackduck** [comment]
Ah so you'll check for changes and reload?

**Comment by khrj** [comment]
> Ah so you'll check for changes and reload?

Yep -- except I'm not checking for changes, I get an event from GitHub (on my server) which I then sign and send to the repl. The daemon on the repl verifies the signature and then the reruns the app (this is explained in the readme -- see "How?")
