### ISSUE TITLE
"gzip: stdin: not in gzip format"

### ISSUE THREAD

**Issue by t3chn0T33n-zz** [KhushrajRathod/repl.deploy#16]
In step 5 of [Usage](https://github.com/KhushrajRathod/repl.deploy#usage):

> Download repl.deploy to the root of your repl -- Open the shell, and run
> `curl -sL https://repl-deploy.vercel.app/ -o repl.deploy.tar.gz` 
> `tar xf repl.deploy.tar.gz`
> `rm repl.deploy.tar.gz`

`tar xf repl.deploy.tar.gz` returns:

`gzip: stdin: not in gzip format`
`tar: Child returned status 1`
`tar: Error is not recoverable: exiting now`

I feel like this is more of a repl.it problem, but I'll still open and issue here just in case...

**Comment by khrj** [comment]
Hey, those instructions are outdated, you should be doing

```bash
curl -sL https://repl-deploy.vercel.app/ -o repl.deploy
chmod +x ./repl.deploy
```

as newer releases (since the rust rewrite) are no longer gzipped.
I've updated the README, thanks for letting me know!
