### ISSUE TITLE
ERROR repl_deploy > Config file doesn't exist?

### ISSUE THREAD

**Issue by UnderBlox** [KhushrajRathod/repl.deploy#19]
I did everything what documentation told me to and I run, then it shows "ERROR repl_deploy > Config file doesn't exist" in the console

**Comment by khrj** [comment]
Hey, did you create the `replit-deploy.json` file? Make sure that exists both on your GitHub repo and your repl

**Comment by UnderBlox** [comment]
Ooh! I created the file in my github repository but forgot to in my repl, sorry and thanks!

**Comment by khrj** [comment]
No problem! :smile:
