### ISSUE TITLE
Public key bin file

### ISSUE THREAD

**Issue by quackduck** [KhushrajRathod/repl.deploy#9]
What's https://github.com/KhushrajRathod/repl.deploy/blob/main/daemon/src/static/public_key.bin for?

**Comment by khrj** [comment]
Every request sent out from the hosted version of the repl.deploy server is signed with a private key, which the daemon then verifies before pulling from github and relaunching the app. This is to prevent random people from pinging your endpoint and effectively getting your repl to restart over and over without any code changes.

If you want to self host the repl.deploy server, there are instructions to make your own public key bin file from an ssh keypair [here](https://github.com/KhushrajRathod/repl.deploy/blob/be79faa370f1cd7c6db424bfa73bccba37438d37/daemon/src/lib.rs#L39)

**Comment by quackduck** [comment]
But why is that file in the tree here on github?

**Comment by khrj** [comment]
Its included as part of the build process & bundled with the daemon
